#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_SENSOR_LOG_LEVEL LOG_LEVEL_DBG
#define CONFIG_ADXL362_ACCEL_RANGE_RUNTIME
#define CONFIG_ADXL362_ACCEL_ODR_RUNTIME
#define CONFIG_ADXL362_TRIGGER_NONE
#define CONFIG_ADXL362_ACTIVITY_THRESHOLD 1000
#define CONFIG_ADXL362_INACTIVITY_THRESHOLD 100
#define CONFIG_ADXL362_INTERRUPT_MODE 0
#define CONFIG_ADXL362_ABS_REF_MODE 0

#define DT_INST_BUS_LABEL(n) "/dev/spidev0.0"
#define DT_INST_REG_ADDR(n) 0
#define DT_INST_LABEL(n) "ADXL362"
#define DT_INST_PROP(n, x) 0
#define DT_INST_SPI_DEV_HAS_CS_GPIOS(x) false
#define DEVICE_AND_API_INIT(a, b, c, d, e, f, g, h)

#endif
